name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set environment variables using secrets and run unit test
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        LOGIN: ${{ secrets.SMTP_LOGIN }}
        PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        TO: gabfestchannel@gmail.com
      run: |
        source venv/bin/activate
        python -m unittest discover

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /python-email-scheduler
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          # Restart any background process or service running the app
