name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Set environment variables using secrets and run unit test
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        LOGIN: ${{ secrets.SMTP_LOGIN }}
        PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        TO: gabfestchannel@gmail.com
      run: |
        source venv/bin/activate
        python -m unittest discover

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd /home/ubuntu/appEmail/python-email-scheduler

          # Check if the virtual environment exists, if not, create it
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          # Pull the latest changes from GitHub
          git pull origin main

          # Activate the virtual environment and install dependencies
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart emailapp
